repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-json
    -   id: check-toml
    -   id: check-yaml
-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    - id: black
-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    - id: flake8
